formatVersion: 1
formatType: am-configuration
---
applications:
  builtinAppsManifestDir: "apps"

logging:
  rules:
    - "*=false"
    - "qt.*=false"
    - "am.*=false"
    - "qml*=true"
    - "*.warning=true"
    - "*.critical=true"

ui:
  fullscreen: no
  mainQml: "SysUI/main.qml"
  
flags:
  noSecurity: yes
  noUiWatchdog: yes

